import type { ModelInfo } from '../../core/src/types/model'

/**
 * A small CURATED catalog of popular open-source models with factual metadata
 * (params, quantization, context, license, runtimes). This is reference data for
 * the model browser and the "What can I run?" analyzer — NOT an exhaustive hub.
 * Sizes are approximate download sizes for the noted quantization.
 *
 * Licenses are shown as declared by the model authors; always verify the model
 * card before commercial use. We never claim a model is free for commercial use.
 */
function b(n: number): number {
  return n * 1024 * 1024 * 1024
}

export const CURATED_MODELS: ModelInfo[] = [
  {
    id: 'llama3.2:3b',
    providerId: 'ollama',
    displayName: 'Llama 3.2 3B Instruct',
    family: 'Llama 3.2',
    organization: 'Meta',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'temperature'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 131072,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 3,
    quantization: 'Q4_K_M',
    architecture: 'llama',
    license: 'Llama 3.2 Community License',
    downloadSizeBytes: b(2),
    diskSizeBytes: b(2),
    supportedRuntimes: ['ollama', 'llamacpp', 'lmstudio'],
    downloads: 2_500_000
  },
  {
    id: 'llama3.1:8b',
    providerId: 'ollama',
    displayName: 'Llama 3.1 8B Instruct',
    family: 'Llama 3.1',
    organization: 'Meta',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'temperature'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 131072,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 8,
    quantization: 'Q4_K_M',
    architecture: 'llama',
    license: 'Llama 3.1 Community License',
    downloadSizeBytes: b(4.7),
    diskSizeBytes: b(4.7),
    supportedRuntimes: ['ollama', 'llamacpp', 'lmstudio'],
    downloads: 5_000_000
  },
  {
    id: 'qwen2.5-coder:7b',
    providerId: 'ollama',
    displayName: 'Qwen2.5 Coder 7B',
    family: 'Qwen2.5',
    organization: 'Alibaba',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'temperature'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 32768,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 7,
    quantization: 'Q4_K_M',
    architecture: 'qwen2',
    license: 'Apache-2.0',
    downloadSizeBytes: b(4.7),
    diskSizeBytes: b(4.7),
    supportedRuntimes: ['ollama', 'llamacpp', 'lmstudio'],
    downloads: 1_800_000,
    notes: 'Strong local coding model.'
  },
  {
    id: 'qwen2.5:14b',
    providerId: 'ollama',
    displayName: 'Qwen2.5 14B Instruct',
    family: 'Qwen2.5',
    organization: 'Alibaba',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'temperature'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 32768,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 14,
    quantization: 'Q4_K_M',
    architecture: 'qwen2',
    license: 'Apache-2.0',
    downloadSizeBytes: b(9),
    diskSizeBytes: b(9),
    supportedRuntimes: ['ollama', 'llamacpp', 'lmstudio'],
    downloads: 1_200_000
  },
  {
    id: 'mistral:7b',
    providerId: 'ollama',
    displayName: 'Mistral 7B Instruct v0.3',
    family: 'Mistral',
    organization: 'Mistral AI',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'temperature'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 32768,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 7,
    quantization: 'Q4_K_M',
    architecture: 'mistral',
    license: 'Apache-2.0',
    downloadSizeBytes: b(4.4),
    diskSizeBytes: b(4.4),
    supportedRuntimes: ['ollama', 'llamacpp', 'lmstudio'],
    downloads: 3_000_000
  },
  {
    id: 'llava:7b',
    providerId: 'ollama',
    displayName: 'LLaVA 7B (Vision)',
    family: 'LLaVA',
    organization: 'LLaVA',
    location: 'local',
    capabilities: ['text', 'streaming', 'vision', 'image_input', 'system_prompt', 'multi_turn'],
    modalities: { input: ['text', 'image'], output: ['text'] },
    contextWindow: 4096,
    maxOutputTokens: 4096,
    supportsTools: false,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 7,
    quantization: 'Q4_K_M',
    architecture: 'llava',
    license: 'Apache-2.0 / LLaMA',
    downloadSizeBytes: b(4.7),
    diskSizeBytes: b(4.7),
    supportedRuntimes: ['ollama'],
    downloads: 900_000,
    notes: 'Multimodal (image understanding).'
  },
  {
    id: 'qwen2.5:32b',
    providerId: 'ollama',
    displayName: 'Qwen2.5 32B Instruct',
    family: 'Qwen2.5',
    organization: 'Alibaba',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'reasoning'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 32768,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: true,
    parameterCount: 32,
    quantization: 'Q4_K_M',
    architecture: 'qwen2',
    license: 'Apache-2.0',
    downloadSizeBytes: b(20),
    diskSizeBytes: b(20),
    supportedRuntimes: ['ollama', 'llamacpp'],
    downloads: 700_000
  },
  {
    id: 'llama3.3:70b',
    providerId: 'ollama',
    displayName: 'Llama 3.3 70B Instruct',
    family: 'Llama 3.3',
    organization: 'Meta',
    location: 'local',
    capabilities: ['text', 'streaming', 'tools', 'system_prompt', 'multi_turn', 'reasoning'],
    modalities: { input: ['text'], output: ['text'] },
    contextWindow: 131072,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsStructuredOutput: false,
    supportsReasoning: true,
    parameterCount: 70,
    quantization: 'Q4_K_M',
    architecture: 'llama',
    license: 'Llama 3.3 Community License',
    downloadSizeBytes: b(43),
    diskSizeBytes: b(43),
    supportedRuntimes: ['ollama', 'llamacpp'],
    downloads: 600_000
  },
  {
    id: 'nomic-embed-text',
    providerId: 'ollama',
    displayName: 'Nomic Embed Text',
    family: 'Nomic Embed',
    organization: 'Nomic',
    location: 'local',
    capabilities: ['text'],
    modalities: { input: ['text'], output: ['embedding'] },
    contextWindow: 8192,
    supportsTools: false,
    supportsStructuredOutput: false,
    supportsReasoning: false,
    parameterCount: 0.137,
    quantization: 'F16',
    architecture: 'nomic-bert',
    license: 'Apache-2.0',
    downloadSizeBytes: b(0.27),
    diskSizeBytes: b(0.27),
    supportedRuntimes: ['ollama'],
    downloads: 1_500_000,
    notes: 'Embedding model.'
  }
]
