/** Large and drawn sample content for the Files tab preview, built when a file is opened. */

const RESOURCES = ['accounts', 'uploads', 'chunks', 'invoices', 'carts', 'orders', 'sessions', 'webhooks', 'tokens', 'reports', 'teams', 'projects', 'assets', 'exports', 'audits']
const ACTIONS: Array<[method: string, suffix: string, name: string]> = [
  ['GET', '', 'index'], ['GET', '/:id', 'show'], ['POST', '', 'create'], ['PATCH', '/:id', 'update'], ['DELETE', '/:id', 'destroy'],
  ['GET', '/:id/history', 'history'], ['POST', '/:id/restore', 'restore'], ['GET', '/search', 'search']
]

/** A 3,000 line route table, the kind of generated file nobody reads top to bottom. */
export function routesSource(): string {
  const lines = [
    '// Generated by scripts/routes.mjs. Do not edit by hand.',
    "import type { Route } from '../router'",
    '',
    'export const routes: Route[] = ['
  ]
  let index = 0
  while (lines.length < 2999) {
    const resource = RESOURCES[index % RESOURCES.length]!
    const action = ACTIONS[Math.floor(index / RESOURCES.length) % ACTIONS.length]!
    const version = 1 + Math.floor(index / (RESOURCES.length * ACTIONS.length))
    if (index % 120 === 0) lines.push(`  // v${version} ${resource}`)
    else lines.push(`  { path: '/v${version}/${resource}${action[1]}', method: '${action[0]}', handler: '${resource}.${action[2]}', auth: ${index % 7 !== 0} },`)
    index++
  }
  lines.push(']')
  return lines.join('\n') + '\n'
}

let events: string[] | undefined
const TYPES = ['upload.chunk', 'upload.retry', 'upload.done', 'auth.refresh', 'cart.add']

function eventLines(): string[] {
  if (events) return events
  events = Array.from({ length: 50_000 }, (_, i) =>
    `{"t":${1759699200000 + i * 137},"type":"${TYPES[i % TYPES.length]}","id":"c_${String(i).padStart(5, '0')}","bytes":${1048576 - (i % 9) * 4096},"status":${i % 23 === 0 ? 429 : 200}}`)
  return events
}

/** The newline-delimited log, cut after `maxBytes` the way the main process cuts a long file. */
export function eventsText(maxBytes: number): { content: string; totalBytes: number; truncated: boolean } {
  const all = eventLines()
  const totalBytes = all.reduce((sum, line) => sum + line.length + 1, 0)
  const kept: string[] = []
  let used = 0
  for (const line of all) {
    if (used + line.length + 1 > maxBytes) break
    kept.push(line)
    used += line.length + 1
  }
  return { content: kept.join('\n') + '\n', totalBytes, truncated: used < totalBytes }
}

/** A 640 by 400 picture drawn on a canvas, as a PNG data URL. */
export function heroPng(): string {
  const canvas = document.createElement('canvas')
  canvas.width = 640
  canvas.height = 400
  const context = canvas.getContext('2d')
  if (!context) return ''
  const sky = context.createLinearGradient(0, 0, 640, 400)
  sky.addColorStop(0, '#2b2f55')
  sky.addColorStop(1, '#0f1020')
  context.fillStyle = sky
  context.fillRect(0, 0, 640, 400)
  for (const [x, y, r, alpha] of [[130, 120, 90, 0.16], [470, 260, 140, 0.1], [330, 90, 50, 0.2]] as const) {
    context.fillStyle = `rgba(143, 161, 255, ${alpha})`
    context.beginPath()
    context.arc(x, y, r, 0, Math.PI * 2)
    context.fill()
  }
  context.fillStyle = '#ececee'
  context.beginPath()
  const [cx, cy, long, short] = [320, 200, 96, 30]
  for (let i = 0; i < 8; i++) {
    const angle = (Math.PI / 4) * i - Math.PI / 2
    const radius = i % 2 === 0 ? long : short
    context[i === 0 ? 'moveTo' : 'lineTo'](cx + Math.cos(angle) * radius, cy + Math.sin(angle) * radius)
  }
  context.closePath()
  context.fill()
  return canvas.toDataURL('image/png')
}
