/** Realistic sample project files for the Files tab preview (`?files=1`). Plain strings, so no module here touches the app. */

const doc = (...lines: string[]): string => lines.join('\n') + '\n'

export const TEXT_FILES: Record<string, string> = {
  'src/upload/client.ts': doc(
    "import { fetchWithAuth } from './auth'",
    "import { withBackoff } from './backoff'",
    "import { UploadError, type Chunk } from './types'",
    '',
    '/**',
    ' * Upload one chunk of a file. Rate limits (429) and server errors (5xx) are retried',
    ' * with exponential backoff and jitter; any other failure is the caller\'s to handle.',
    ' * When the server sends Retry-After, that delay wins if it is longer than the backoff.',
    ' */',
    'export async function uploadChunk(chunk: Chunk) {',
    '  return withBackoff(async () => {',
    '    const res = await put(chunk)',
    "    const wait = res.headers.get('retry-after')",
    '    if (!res.ok) throw new UploadError(res.status, wait)',
    '    return res.json()',
    '  }, retryAfter, { retries: 4, baseMs: 250 })',
    '}',
    '',
    'async function put(chunk: Chunk): Promise<Response> {',
    "  const body = new Blob([chunk.bytes], { type: 'application/octet-stream' })",
    "  return fetchWithAuth('/v1/uploads/' + chunk.uploadId + '/chunks/' + chunk.index, {",
    "    method: 'PUT',",
    "    headers: { 'content-length': String(chunk.bytes.byteLength) },",
    '    body',
    '  })',
    '}',
    '',
    'function retryAfter(error: unknown): number | null {',
    '  if (!(error instanceof UploadError)) return null',
    '  if (error.status !== 429 && error.status < 500) return null',
    '  const seconds = Number(error.retryAfter)',
    '  return Number.isFinite(seconds) ? seconds * 1000 : 0',
    '}',
    '',
    '// Chunks upload one at a time: the API rejects parallel writes to the same upload.',
    'export async function uploadFile(uploadId: string, bytes: Uint8Array, chunkSize = 1 << 20): Promise<number> {',
    '  let index = 0',
    '  for (let offset = 0; offset < bytes.byteLength; offset += chunkSize) {',
    '    await uploadChunk({ uploadId, index, bytes: bytes.subarray(offset, offset + chunkSize) })',
    '    index++',
    '  }',
    '  return index',
    '}'
  ),

  'src/upload/backoff.ts': doc(
    'export interface BackoffOptions { retries: number; baseMs: number; maxMs?: number }',
    '',
    'const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms))',
    '',
    '/** Retry `task` with exponential backoff and jitter. `delayFor` returns a server-requested delay in ms, or null to give up. */',
    'export async function withBackoff<T>(',
    '  task: () => Promise<T>,',
    '  delayFor: (error: unknown) => number | null,',
    '  { retries, baseMs, maxMs = 8000 }: BackoffOptions',
    '): Promise<T> {',
    '  for (let attempt = 0; ; attempt++) {',
    '    try {',
    '      return await task()',
    '    } catch (error) {',
    '      const requested = delayFor(error)',
    '      if (requested === null || attempt >= retries) throw error',
    '      const backoff = Math.min(maxMs, baseMs * 2 ** attempt)',
    '      await sleep(Math.max(requested, backoff * (0.5 + Math.random() / 2)))',
    '    }',
    '  }',
    '}'
  ),

  'src/upload/types.ts': doc(
    'export interface Chunk {',
    '  uploadId: string',
    '  index: number',
    '  bytes: Uint8Array',
    '}',
    '',
    'export class UploadError extends Error {',
    '  constructor(',
    '    readonly status: number,',
    '    readonly retryAfter?: string | null',
    '  ) {',
    "    super('Upload failed with status ' + status)",
    "    this.name = 'UploadError'",
    '  }',
    '}'
  ),

  'src/upload/auth.ts': doc(
    "const TOKEN_KEY = 'lumen.token'",
    '',
    'export function currentToken(): string | null {',
    '  return localStorage.getItem(TOKEN_KEY)',
    '}',
    '',
    'export async function fetchWithAuth(url: string, init: RequestInit = {}): Promise<Response> {',
    '  const token = currentToken()',
    '  const headers = new Headers(init.headers)',
    "  if (token) headers.set('authorization', 'Bearer ' + token)",
    '  return fetch(url, { ...init, headers })',
    '}'
  ),

  'src/upload/client.test.ts': doc(
    "import { describe, expect, it, vi } from 'vitest'",
    "import { uploadChunk } from './client'",
    '',
    'const chunk = { uploadId: \'u1\', index: 0, bytes: new Uint8Array([1, 2, 3]) }',
    'const reply = (status: number, headers: Record<string, string> = {}) => new Response(\'{}\', { status, headers })',
    '',
    "describe('uploadChunk', () => {",
    "  it('retries a 429 and honors Retry-After', async () => {",
    '    vi.useFakeTimers()',
    "    const put = vi.fn().mockResolvedValueOnce(reply(429, { 'retry-after': '2' })).mockResolvedValueOnce(reply(200))",
    '    const done = uploadChunk(chunk, { put })',
    '    await vi.advanceTimersByTimeAsync(2000)',
    '    await expect(done).resolves.toBeDefined()',
    '    expect(put).toHaveBeenCalledTimes(2)',
    '  })',
    '',
    "  it('gives up after four retries', async () => {",
    '    const put = vi.fn().mockResolvedValue(reply(503))',
    '    await expect(uploadChunk(chunk, { put, baseMs: 0 })).rejects.toThrow(UploadError)',
    '    expect(put).toHaveBeenCalledTimes(5)',
    '  })',
    '',
    "  it('does not retry a 400', async () => {",
    '    const put = vi.fn().mockResolvedValue(reply(400))',
    '    await expect(uploadChunk(chunk, { put })).rejects.toThrow(UploadError)',
    '    expect(put).toHaveBeenCalledTimes(1)',
    '  })',
    '})'
  ),

  'src/checkout/cart.ts': doc(
    'export interface CartLine { sku: string; unitCents: number; quantity: number }',
    '',
    'export function totalCents(lines: readonly CartLine[], discountPercent = 0): number {',
    '  const subtotal = lines.reduce((sum, line) => sum + line.unitCents * line.quantity, 0)',
    '  return Math.round(subtotal * (1 - discountPercent / 100))',
    '}',
    '',
    'export function addLine(lines: readonly CartLine[], next: CartLine): CartLine[] {',
    '  const existing = lines.find((line) => line.sku === next.sku)',
    '  if (!existing) return [...lines, next]',
    '  return lines.map((line) => (line === existing ? { ...line, quantity: line.quantity + next.quantity } : line))',
    '}'
  ),

  'src/checkout/cart.test.ts': doc(
    "import { describe, expect, it } from 'vitest'",
    "import { addLine, totalCents } from './cart'",
    '',
    "describe('cart', () => {",
    "  it('adds a line once and then raises its quantity', () => {",
    "    const first = addLine([], { sku: 'a', unitCents: 500, quantity: 1 })",
    "    expect(addLine(first, { sku: 'a', unitCents: 500, quantity: 2 })[0]?.quantity).toBe(3)",
    '  })',
    '',
    "  it('applies a percentage discount to the total', () => {",
    "    expect(totalCents([{ sku: 'a', unitCents: 1000, quantity: 2 }], 25)).toBe(1500)",
    '  })',
    '})'
  ),

  'README.md': doc(
    '# Lumen web',
    '',
    'The marketing site and upload console for Lumen. Built with Vite and TypeScript.',
    '',
    '## Getting started',
    '',
    '```bash',
    'npm install',
    'npm run dev',
    '```',
    '',
    'The dev server starts on port 5173 and reloads when you save a file.',
    '',
    '## Scripts',
    '',
    '| Script | What it does |',
    '| --- | --- |',
    '| `npm run dev` | Start the dev server |',
    '| `npm test` | Run the unit tests once |',
    '| `npm run build` | Type-check and build for production |',
    '',
    '## Project layout',
    '',
    '- `src/upload` holds the chunked upload client and its retry policy.',
    '- `src/checkout` holds the cart and totals.',
    '- `src/generated` is written by `scripts/routes.mjs`. Do not edit it by hand.',
    '',
    '> Uploads retry on 429 and 5xx with exponential backoff. A 400 fails on the first attempt.',
    '',
    '## Contributing',
    '',
    'Keep changes small, add tests next to the code, and run `npm test` before you push.'
  ),

  'CHANGELOG.md': doc(
    '# Changelog',
    '',
    '## 1.4.0',
    '',
    '- Uploads retry on 429 and 5xx with exponential backoff, honoring Retry-After.',
    '- The cart total applies percentage discounts before rounding.',
    '',
    '## 1.3.2',
    '',
    '- Fix a flaky checkout test that depended on the system clock.',
    '- Update Vite to 7.0.',
    '',
    '## 1.3.1',
    '',
    '- Dark mode tokens for the upload console.'
  ),

  'package.json': doc(
    '{',
    '  "name": "lumen-web",',
    '  "version": "1.4.0",',
    '  "private": true,',
    '  "type": "module",',
    '  "scripts": {',
    '    "dev": "vite",',
    '    "build": "tsc --noEmit && vite build",',
    '    "test": "vitest run"',
    '  },',
    '  "dependencies": {',
    '    "react": "^18.3.1",',
    '    "react-dom": "^18.3.1"',
    '  },',
    '  "devDependencies": {',
    '    "typescript": "^5.7.2",',
    '    "vite": "^7.0.0",',
    '    "vitest": "^2.1.8"',
    '  }',
    '}'
  ),

  'tsconfig.json': doc(
    '{',
    '  "compilerOptions": {',
    '    "target": "ES2022",',
    '    "module": "ESNext",',
    '    "moduleResolution": "Bundler",',
    '    "strict": true,',
    '    "noUncheckedIndexedAccess": true,',
    '    "skipLibCheck": true',
    '  },',
    '  "include": ["src"]',
    '}'
  ),

  'vite.config.ts': doc(
    "import { defineConfig } from 'vite'",
    '',
    'export default defineConfig({',
    '  server: { port: 5173 },',
    "  build: { target: 'es2022', sourcemap: true }",
    '})'
  ),

  '.github/workflows/ci.yml': doc(
    'name: ci',
    'on:',
    '  push:',
    '    branches: [main]',
    '  pull_request:',
    '',
    'jobs:',
    '  test:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 22',
    '      - run: npm ci',
    '      - run: npm test'
  ),

  '.gitignore': doc('node_modules', 'dist', '.env', '*.log'),

  '.env.example': doc('API_BASE_URL=https://api.example.test', 'UPLOAD_CHUNK_BYTES=1048576'),

  'assets/mark.svg': doc(
    '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">',
    '  <rect width="160" height="160" rx="28" fill="#1b1b1d"/>',
    '  <path d="M80 28 L96 64 L132 80 L96 96 L80 132 L64 96 L28 80 L64 64 Z" fill="#e9e9ec"/>',
    '</svg>'
  ),

  // Windows line endings on purpose, so the status bar can say CRLF.
  'scripts/setup.ps1': [
    '$ErrorActionPreference = "Stop"',
    '',
    'Write-Host "Installing dependencies"',
    'npm ci',
    '',
    'if (-not (Test-Path .env)) {',
    '  Copy-Item .env.example .env',
    '  Write-Host "Created .env from .env.example"',
    '}',
    ''
  ].join('\r\n')
}
